service: serverless-boilerplate

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

provider:
  name: aws
  runtime: nodejs12.x
  memorySize: 128
  stage: api
#  region: us-east-1

package:
  exclude:
    - .gitignore
    - .git/**

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: /ping
          method: get
